# These are supported funding model platforms

github: @devinschumacher
custom: https://www.youtube.com/@devinschumacher/membership
patreon: devinschumacher
ko_fi: devinschumacher
buy_me_a_coffee: devinschumacher
